# Generated by Django 4.2 on 2023-09-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agenda", unique_together={("data", "hora", "profissional")},
        ),
    ]
