# Generated by Django 4.2 on 2023-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="atendimentos", name="servicos",),
        migrations.AddField(
            model_name="atendimentos",
            name="servicos",
            field=models.ManyToManyField(to="core.servicos"),
        ),
    ]
