# Generated by Django 4.2 on 2023-09-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_especialidades_servicos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atendimentos",
            name="servicos",
            field=models.CharField(max_length=100),
        ),
    ]
