# Generated by Django 4.2 on 2023-09-03 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profissional_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissional",
            name="dt_cadastro",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="profissional",
            name="estrelas",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profissional",
            name="qtd_atds",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
