# Generated by Django 4.2 on 2023-09-04 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profissional_dt_cadastro_profissional_estrelas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissional",
            name="dt_cadastro",
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
